input {
  beats {
    port => 5044
  }
}

filter {
  json {
    source => "message"
  }

  mutate {
    convert => { "level" => "integer" }
  }

  if [level] <= 5 {
    mutate { add_field => { "convert_level" => "LOW" } }
  } else {
    mutate { add_field => { "convert_level" => "HIGH" } }
  }

  # Snapshot 1
  ruby {
    code => 'puts "[SNAPSHOT 1 - Stage 1] Event processed: ID=#{event.get("id")}, convert_level=#{event.get("convert_level")}"'
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "raw-to-input"
  }
}
