input {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "raw-to-input"
    schedule => "* * * * * *"
  }
}

filter {
  if [convert_level] == "HIGH" {
    mutate { add_field => { "type" => "OK" } }
  } else {
    mutate { add_field => { "type" => "PENDING" } }
  }

  # Snapshot 2
  ruby {
    code => 'puts "[SNAPSHOT 2 - Stage 2] Event processed: ID=#{event.get("id")}, type=#{event.get("type")}"'
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "input-to-sec"
  }
}
